"use client"


// import type { Metadata } from "next";
import { Montserrat } from "next/font/google";
import "./globals.css";
import Header from "./components/Header";
import Footer from "./components/Footer";
import Unlock from "./components/Unlock";
import { Provider } from "react-redux";
import { store } from "../redux/store";


const montserrat = Montserrat({
  subsets: ['latin'], // Add subsets you need
  weight: ['400', '500', '600', '700', '800', '900'], // Add weights you need
});


// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={montserrat.className}
      >
        <Provider store={store}>
          <Header />
          {children}
          <Unlock />
          <Footer />
        </Provider>
      </body>
    </html>
  );
}
